development:
  GOOGLE_CLIENT_ID: 'YOUR_GOOGLE_CLIENT_ID'
  GOOGLE_SECRET_ID: 'YOUR_GOOGLE_SECRET_ID'
  FACEBOOK_CLIENT_ID: 'YOUR_FACEBOOK_CLIENT_ID'
  FACEBOOK_SECRET_ID: 'YOUR_FACEBOOK_SECRET_ID'
test:
  GOOGLE_CLIENT_ID: 'MY_GOOGLE_CLIENT_ID_FOR_TEST'
  GOOGLE_SECRET_ID: 'MY_GOOGLE_SECRET_ID_FOR_TEST'
  FACEBOOK_CLIENT_ID: 'MY_FACEBOOK_CLIENT_ID_FOR_TEST'
  FACEBOOK_SECRET_ID: 'MY_FACEBOOK_SECRET_ID_FOR_TEST'
